name: Deploy Laravel App to Hostinger

on:
  push:
    branches:
      - main  # O el nombre de la rama que uses

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Ajusta según la versión de PHP que uses
          extensions: mbstring, exif, pcntl, bcmath, gd
          ini-values: post_max_size=256M, upload_max_filesize=256M, max_execution_time=300
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.hardcode.com.co
          username: u116066788.hardapi
          password: Escorpi777.
          local-dir: ./  # Especifica el directorio correcto de tu proyecto Laravel
          server-dir: ./


      - name: Set permissions
        run: |
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;
          chmod -R 777 storage
          chmod -R 777 bootstrap/cache
