name: Deploy Laravel App to Hostinger

on:
  push:
    branches:
      - main  # O el nombre de la rama que uses

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Ajusta según la versión de PHP que uses
          extensions: mbstring, exif, pcntl, bcmath, gd
          ini-values: post_max_size=256M, upload_max_filesize=256M, max_execution_time=300
          coverage: none

      - name: Exclude vendor and node_modules
        run: echo -e "vendor/\nnode_modules/" > .ftpignore

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  
          server-dir: ./
          exclude: |
            vendor/
            node_modules/

      - name: Execute SSH commands on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /domains/hardcode.com.co/public_html/api/
            composer install --no-interaction --prefer-dist --optimize-autoloader
